language: node_js
os: linux
sudo: required
dist: trusty
group: travis_lts

notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
    on_success: change
    on_failure: always

cache:
  directories:
    - "$HOME/.npm"

node_js:
  - '8'

addons:
  chrome: stable

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgif-dev
  - npm i -g npm@6.0.1 # this should be deleted once 5.7.X is out of "pre-release"
  - npm install -g canvas@1.6.9

install:
  - npm ci

script:
  - npm run build:release -- --bail
  - npm run test:travis
  - git config --global user.name "Travis CI"
  - git config --global user.email "sebastien.jourdain@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/Kitware/paraviewweb.git
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run doc:publish; fi

after_success:
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
